import Hero from "@/components/Hero"
import Navbar from "@/components/Navbar"
import Head from "next/head"
import { AiFillBook, AiOutlineSearch } from "react-icons/ai"
import { MdCompare } from "react-icons/md"

export default function Home() {
  return (
    <div>
      <Head>
        <title>u-Mov</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <>
        <div
          className="h-[100dvh] bg-[#EEEEEE] px-6 py-4 dark:bg-gradient-to-b 
        dark:from-[#000000] dark:via-darkgray dark:to-darkgray dark:text-white lg:px-20 "
        >
          {/* Nav */}
          <Navbar />
          {/* Main  */}
          <main className="md:flex md:flex-col md:gap-20 md:px-20 md:py-44">
            {/* hero */}
            <Hero />
          </main>
          {/* hook */}
          <div className="flex h-[350px] flex-col items-center justify-between gap-10">
            <h2 className="font-lilita text-6xl">All the advantages</h2>

            <ul className="flex w-full justify-between">
              <li className="h-60 w-96 p-4 dark:bg-darkgray ">
                <div className="flex items-center gap-2 text-3xl">
                  <MdCompare />
                  <h3 className="text-2xl font-bold">Compare</h3>
                </div>
                <p>
                  Compare everything side by side and make the decision that
                  suits you the best
                </p>
              </li>
              <li className="h-60 w-96 p-4 dark:bg-darkgray ">
                <div className="flex items-center gap-2 text-3xl">
                  <AiOutlineSearch />
                  <h3 className="text-2xl font-bold">Search</h3>
                </div>
                <p>You dont know the location? use our extension</p>
              </li>
              <li className="h-60 w-96 p-4 dark:bg-darkgray ">
                <div className="flex items-center gap-2 text-3xl">
                  <AiFillBook />
                  <h3 className="text-2xl font-bold">Research</h3>
                </div>
                <p>Research every fact before you move</p>
              </li>
            </ul>
          </div>
        </div>
        {/*  */}
        <div className="h-[800px] dark:bg-darkgray"></div>
        <div className="h-[800px] dark:bg-darkgray"></div>
      </>
    </div>
  )
}
