const routeWithoutTraffic = {
    origin: string,
    destination: string,
    intermediates: string,
    nonPendularDepartureTime: string,
    travelMode: string,
    routingPreference: string,
    avoidTolls: boolean,
    avoidHighways: boolean,
    avoidFerries: boolean,                                             
    numberOfTravels: number,
    typeOfEngine: string,
    fuelConsumption: number,
    energyConsumptionEletric: number,
    isPendularRoute: boolean,
    pendularRouteId: number,
    outboundTimePendular: string,
    inboundTimePendular: string,
  }